
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-01T21:17:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b58b27b506e0d84d21a2cfd775edc18693acb5ed",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
