# -*- coding: utf-8 -*-
#
# pyCMW documentation build configuration file, created by
# sphinx-quickstart on Mon Sep 01 21:59:30 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..')) #/pyiron'))
sys.path.insert(0, os.path.abspath('..')) #/pyiron'))

import pyiron.workbench
