{% set data = load_setup_py_data() %}

package:
  name: pyiron_vasp
  version: {{ data.get('version') }}

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyiron_base
    - pyiron_atomistics
    - pyiron_dft
    - lxml

  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyiron_atomistics
    - pyiron_dft
    - lxml

build:
  noarch: python
  script_env:
   - TRAVIS
   - APPVEYOR

test:
  imports:
    - pyiron_vasp

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyiron vasp plugin"
