package:
  name: pyiron_vasp
  version: beta

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyiron_base
    - pyiron_atomistics
    - pyiron_dft

  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyiron_atomistics
    - pyiron_dft

build:
  script_env:
   - TRAVIS
   - APPVEYOR

test:
  imports:
    - pyiron_vasp

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyiron vasp plugin"
