#!/usr/bin/env python3.7
"""
Prints jobs from pyiron project.
"""

import argparse
import sys
import pandas as pd
import pyiron

parser = argparse.ArgumentParser(description = __doc__)
parser.add_argument(
        "project", default = ".", nargs = "?",
        help = "path to pyiron project"
)
parser.add_argument(
        "-c", "--columns", nargs = "+",
        default = ("id", "status", "job", "timestart", "timestop"),
        help = "table columns to print, pass 'all' to print whole table"
)

args = parser.parse_args()

# a[slice(None)] == a[:] for all a
columns = args.columns if "all" not in args.columns else slice(None)
print(pyiron.Project(args.project).job_table(full_table = True).loc[:, columns])
